//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    using DataAccess;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.Plays_ON = new HashSet<Plays_ON>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FinalScore { get; set; }
        public Nullable<int> HomeTeamScore { get; set; }
        public Nullable<int> AwayTeamScore { get; set; }
        public string AwayTeamName { get; set; }
        public string HomeTeamName { get; set; }
        public int StadiumID { get; set; }
        public int TeamID { get; set; }
    
        public virtual Stadium Stadium { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plays_ON> Plays_ON { get; set; }
    }
}
