//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DataAccess;
    
    public partial class FootballManagementSystemEntities : DbContext
    {
        public FootballManagementSystemEntities()
            : base("name=FootballManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<League> League { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Plays_ON> Plays_ON { get; set; }
        public virtual DbSet<Stadium> Stadium { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Transfer> Transfer { get; set; }
        public virtual DbSet<Transferred> Transferred { get; set; }
    }
}
