//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using DataAccess;
    [DataContract]
    public partial class Transferred
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public int TransferID { get; set; }
        [DataMember]
        public int PlayerID { get; set; }
        [DataMember]
        public int TeamID { get; set; }
        [DataMember]
        public string NewTeam { get; set; }
        [DataMember]
        public string OldTeam { get; set; }
        [IgnoreDataMember]
        public virtual Player Player { get; set; }
        [IgnoreDataMember]
            public virtual Team Team { get; set; }
        [IgnoreDataMember]
        public virtual Transfer Transfer { get; set; }
    }
}
